### ISSUE TITLE
[Suggestion] Rename the 'name' constant to 'scriptname'

### ISSUE THREAD

**Issue by DeepCoreSystem** [ioBroker/ioBroker.javascript#100]
Personally, I prefer 'speaking names' for variables. Therefore I would like to suggest the renaming of the script name constant from 'name' to 'scriptname'. 
I think it will make someone's life easier when debugging.

**Comment by Apollon77** [comment]
"Renaming" in fact would mean "have two identified available" because we can not break backward compatibility. And in fact also the introduction of the new identifier will bring potentiasl backward compatibility problems for people that use an own identifier called "scriptname" in the meantime.

I understand the intention of your request, but I personally would decline it because of the reasons above.

**Comment by GermanBluefox** [comment]
scriptName added

**Comment by AlCalzone** [comment]
Reminder for me to add it to the declarations file @AlCalzone

**Comment by AlCalzone** [comment]
done!
