### ISSUE TITLE
Newly created aliases (alias.0.xxx) is not accessible via `getState` or `existsState` without adapter restart

### ISSUE THREAD

**Issue by PeterVoronov** [ioBroker/ioBroker.javascript#1003]
**Describe the bug**  
If I create any alias (via devices, manually, etc..) I can't access to its state till the JavaScript adapter will be restarted.
If I try to run `existsState` - it will return `false`;
If I try to run `getState` it will return 
```
{
 "val": null,
 "notExist": true
}
```
and generate an warning in log:
```
warn: javascript.0 (2163019) getState "alias.0.Device_5.ACTUAL" not found (3)
```

After restarting the JavaScript adapter everything is working like a charm.

**To Reproduce**  
1. Go to Devices.
2. Create any alias device.
3. Make any script with `getState` or `existsState` targeted on any newly created alias state.
4. See error (see above)
5. Restart JavaScript adapter.
6. Error is gone.

**Expected behavior**  
Access to the aliased state without JavaScript adapter restart.

**Screenshots & Logfiles**  
See above

**Versions:**  
 - Adapter version: 5.5.4
 - JS-Controller version: 4.0.21
 - Node version: 14.19.1
 - Operating system: Debian 11

**Comment by Apollon77** [comment]
One question: When you do exactly what you did above, but then change the value of that alias ... is getState then returning a value or still "Not existing"?

**Comment by PeterVoronov** [comment]
> One question: When you do exactly what you did above, but then change the value of that alias (or the "underlaying state) ... is getState then returning a value or still "Not existing"?

In this case yes, it's accessible, but for some states, which changed rarely it still require the adapter reboot.

**Comment by Apollon77** [comment]
Ok, then I know the reason :-) Will do a fix later and then you can check it from GitHub.

The reason is the following: When you create a normal object and add e.g. a default value or set a value afterwards then both gets published and the running javascript adapter will "see" and remember it.

AN Alias by himself do not have a state value. This means that on alias object creation there might exist a current value alteady but this value is not "published" - just if there is a change.

So the fix I will do is, that, when an alias object got created the javascript adapter will actively read the value for his internal value store directly when he got the object publish. With this it should have the "last value" of the alias available

**Comment by Apollon77** [comment]
Hi, please try GitHub version

**Comment by PeterVoronov** [comment]
> Hi, please try GitHub version

Tried, excuse me, I didn't see any changes in result. The same behavior without restart the adapter...
```
info: javascript.0 (3480602) script.js.Test.Script_1_1: existsState = false
warn: javascript.0 (3480602) getState "alias.0.Test.tst" not found (3)
warn: javascript.0 (3480602)     at script.js.Test.Script_1_1:48:42
warn: javascript.0 (3480602)     at script.js.Test.Script_1_1:57:3
info: javascript.0 (3480602) script.js.Test.Script_1_1: getState = {
 "val": null,
 "notExist": true
}
```

**Comment by Apollon77** [comment]
Ok, try again please ... was a typo :-)

**Comment by PeterVoronov** [comment]
QA task is done.
Tested successfully.
Thank you.

**Comment by Apollon77** [comment]
Release will come later today
