### ISSUE TITLE
Blockly Javascript Funktion

### ISSUE THREAD

**Issue by Snigga** [ioBroker/ioBroker.javascript#1065]
Text wird leider rechts nach links geschrieben  Aus var wird rav.

**Versions:**  
 - Adapter version: 5.8.5
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0

**Comment by Apollon77** [comment]
Wo? Nur in Blockly oder auch im normalen Editor?

**Comment by winnyschuster** [comment]
> Wo? Nur in Blockly oder auch im normalen Editor?

nur in Blockly und dort nur in den beiden Javascript-Funktionen(mit und ohne Rückgabe). Die Textblöcke sind nicht betroffen

**Comment by Diginix** [comment]
@winnyschuster Kannst du davon mal ein Screenshot posten?
Bei mir sehen alle JS Funktionen in Blockly wie gewohnt und ok aus, aber vllt finde ich die Stelle nicht.

**Comment by winnyschuster** [comment]
> @winnyschuster Kannst du davon mal ein Screenshot posten? Bei mir sehen alle JS Funktionen in Blockly wie gewohnt und ok aus, aber vllt finde ich die Stelle nicht.

einfach mal was reinschreiben :-) passiert mit v5.8.5

**Comment by Diginix** [comment]
Stimmt, hab nur die existierenden geöffnet. Aber sobald man etwas schreibt springt der Cursor in Zeile 1 Spalte 1 und alles wird RTL eingefügt. Echt mal ein "kreativer" Bug.

**Comment by klein0r** [comment]
The issue is caused by the setState after onchange event:

https://github.com/ioBroker/ioBroker.javascript/blob/1ee9807313ad54c4391a2f02618d5d0582d6d646/src/src/Components/ScriptEditorVanilaMonaco.jsx#L104-L105

https://github.com/ioBroker/ioBroker.javascript/blob/1ee9807313ad54c4391a2f02618d5d0582d6d646/src/src/Dialogs/ScriptEditor.jsx#L75

It seems like the ``setState`` changes the focus of the component

**Comment by Diginix** [comment]
works fine again with 5.8.7
