### ISSUE TITLE
Provide declarations for user-installed npm modules

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/ioBroker.javascript#130]
After #124 is merged, it would be nice to also provide declaration files for externally installed npm modules (like from the adapter configuration dialog).

Therefore a couple of things have to be done:
- [ ] install the corresponding `@types/<modulename>` package if it exists. This should use the proposed utility functions in https://github.com/ioBroker/ioBroker.js-controller/issues/202
- [x] or retrieve the declaration files contained in the module itself, if there are any
- [x] alternatively, only lookup already installed `@types/<modulename>` packages
- [x] provide those declarations to the editor and TS compiler

**Comment by AlCalzone** [comment]
Everything but the first point is done in #422

**Comment by WolfspiritM** [comment]
I tried to use typescript with some external modules but this doesn't work for me at all.
Maybe I'm missing something...

```
import * as codepage from "codepage";
^ ERROR: Cannot find module 'codepage' or its corresponding type declarations.
import * as xml2js from "xml2js";
^ ERROR: Cannot find module 'xml2js' or its corresponding type declarations.
import * as mqtt from "mqtt";
^ ERROR: Cannot find module 'mqtt' or its corresponding type declarations.
```

I then tried to add these modules to the "Activate syntax help for these npm modules" box and then the adapter fails to start completly:
```
Caught by controller[0]: Failed to load definitions for codepage: Error: ENOENT: no such file or directory, open '/opt/iobroker/node_modules/iobroker.javascript/node_modules/codepage/types.d.ts'
```
I thought maybe I can fake that by using codepage/types instead of just codepage in that dialog but then xml2js fails aswell:
```
Error: The file /opt/iobroker/node_modules/iobroker.js-controller/@types/mqtt/types/lib/store.d.ts doesn't exist
```

It's missing the "node_modules" folder here.
I think something is wrong with the "types" parsing of the package.json?

**Comment by AlCalzone** [comment]
The paths the adapter is looking in are pretty weird, I need to check that.

**Comment by WolfspiritM** [comment]
I investigated a bit more:
The xml2js error is my bad cause I was missing @types/xml2js

The first error with codepage seems to be that codepage they've specified "types" as a folder. The adapter seems to add a ".d.ts" to it and then uses that as the file instead of using the index.d.ts inside the "types" folder.

The other problem seems to be that typescript out of whatever reason seems to append the path to the getScriptVersion and that whole path can't be found in the virtual file system.

```
Error: The file /opt/iobroker/node_modules/iobroker.js-controller/@types/mqtt/types/lib/store.d.ts doesn't exist
    at VirtualFileSystem.getFileVersion (/opt/iobroker/node_modules/iobroker.javascript/node_modules/virtual-tsc/build/virtual-fs.js:74:19)
    at InMemoryServiceHost.getScriptVersion (/opt/iobroker/node_modules/iobroker.javascript/node_modules/virtual-tsc/build/service-host.js:23:24)
    at /opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:139179:136
    at sourceFileVersionUptoDate (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:99929:43)
    at sourceFileNotUptoDate (/opt/iobroker/node_modules/iobroker.javascript/node_modules/typescript/lib/typescript.js:99925:21)
```

**Comment by Apollon77** [comment]
Sentry reported: https://sentry.iobroker.net/organizations/iobroker/issues/2616/
