### ISSUE TITLE
7.1.0 Blöcke werden in Englisch angezeigt

### ISSUE THREAD

**Issue by Voodoo2man** [ioBroker/ioBroker.javascript#1338]
Teilweise werden die Blöcke in Englisch angezeigt.
Blöcke aus den Bereichen Logik, Schleifen, Mathematik, Text, Listen, Farbe, Variablen und Funktionen sind betroffen.

 - Adapter version: 7.1.0
 - JS-Controller version: 5.0.2
 - Node version: 18.13.0
 - Operating system: Raspberry OS

<img width="349" alt="image" src="https://github.com/ioBroker/ioBroker.javascript/assets/62031459/ab46e93a-355e-4d9d-9031-52631d110566">

**Comment by BlackandGold1** [comment]
hab das gleiche Problem. Wie geht es jetzt weiter? was kann ich tun?

**Comment by skvarel** [comment]
Ich habe nach dem Merge die Version erneut von GitHub aus installiert. Die Blöcke sind immer noch in englisch.

![image](https://github.com/ioBroker/ioBroker.javascript/assets/1114419/bc1627b5-b04b-41df-9674-49914ee2c8f9)

**Comment by Diginix** [comment]
Auch mit 7.1.1 sind viele Blöcke weiterhin nur Englisch. Bluefox plant aber die 7.1.1 als stable zu veröffentlichen (#1362). Der PR von @klein0r ist aber gemerged.

**Comment by Diginix** [comment]
Genau deswegen fände ich die 7.1.1 als stable eher unpassend.

**Comment by klein0r** [comment]
Wer will denn 7.1.1 auf stable stellen?!?!

**Comment by Apollon77** [comment]
@ice987987 The Repo Stable PR is created automatically after a certain time or certain beta installations, so all fine. Please comment in the STable PR so that it is know that this should wait.

Bluefox was on vacatio for a week and do not wanted to push a version short before that without a chance to potentially react. So a fix with the PR will come soon
