### ISSUE TITLE
4.0.5 Cannot extract Blockly code!

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.javascript#284]
Bei jedem erstem Öffnen der Scripte kommt folgende Meldung:

Cannot extract Blockly code!

Sobald man ein anderes Script auswählt funktioniert es wieder.

Fehlermeldungen:

`BlocklyEditor.js:359 ReferenceError: scripts is not defined
    at Blockly.FieldDropdown.menuGenerator_ (blocks_timeout.js:274)
    at Blockly.FieldDropdown.getOptions_ (blockly_compressed.js:1271)
    at new Blockly.FieldDropdown (blockly_compressed.js:1265)
    at Blockly.BlockSvg.init (blocks_timeout.js:273)
    at Blockly.BlockSvg.Blockly.Block (blockly_compressed.js:1077)
    at new Blockly.BlockSvg (blockly_compressed.js:1129)
    at Blockly.WorkspaceSvg.newBlock (blockly_compressed.js:1027)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:1004)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:1006)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:1007)`

**Comment by DutchmanNL** [comment]
bitte mit F11 console error output aktivieren und dieses issue mit den Fehlermeldungen ergänzen

**Comment by Ilovegym66** [comment]
Version 4.1.0 mit js-controller 1.5.7 ganz extrem, fast jedes Blockly kann man gar nicht mehr bearbeiten, manchmal durch hin- und her klicken zwischen javascript-script und blockly-script gehts dann. 
Bin zurück auf die 4.0.12 und jetzt ist der 'cannot extract blockly code'  absolut weg.
( ist ja gut, aber warum, vorher war da in dieser Version mit js-controller 1.5.3 auch da) aber obs am js-controller liegt???

**Comment by aleks-83** [comment]
Ich nutze auch JS-controller 1.5.7 mit JS Adapter 4.1.0.
Fast alle Skripte kann ich aufrufen, aber 2 nicht.
Wenn ich auf JavaScript Anzeige umschalte, sehe ich den Code, schalte ich zurück (egal wie oft hin und her), bekomme ich die Meldung: Cannot extract blockly Code.

Wird es bald eine Möglichkeit geben, ein JS Skript in ein Blocky zurück zu wandeln?
Oder ist das technisch nicht möglich?

**Comment by Ilovegym66** [comment]
> bitte mit F11 console error output aktivieren und dieses issue mit den Fehlermeldungen ergänzen

F11 ist der Vollbildmodus, das bringt nicht viel - Du meinst bestimmt im Menu Tools auf Developer/Webdeveloper und dann Browser-Console aufrufen :-)

Hier mal ein Output mit GoogleChrome, im anderen Issue hab ich den Output von Firefox gepostet:
`:8081/#tab-instances:1 Active resource loading counts reached a per-frame limit while the tab was in background. Network requests will be delayed until a previous loading finishes, or the tab is brought to the foreground. See https://www.chromestatus.com/feature/5527160148197376 for more details
jquery.fancytree-all.js:113 Fancytree@1 Fancytree.filterNodes() leavesOnly option is deprecated since 2.9.0 / 2015-04-19. Use opts.leavesOnly instead.
c @ jquery.fancytree-all.js:113
adminInstances.js:1032 65
Connection.js:229 Subscribe logs
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}.
blockly_compressed.js:893 WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}.
BlocklyEditor.js:92 Detected custom blockly: cloud
BlocklyEditor.js:92 Detected custom blockly: iot
BlocklyEditor.js:92 Detected custom blockly: email
i18n.js:41 Translate: Filter by
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Filter by
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Close all but current
i18n.js:41 Translate: Close all but current
5i18n.js:41 Translate: Filter by
i18n.js:41 Translate: Close all but current
BlocklyEditor.js:359 TypeError: Unknown block type: telegram
    at Blockly.BlockSvg.Blockly.Block (blockly_compressed.js:1404)
    at new Blockly.BlockSvg (blockly_compressed.js:1467)
    at Blockly.WorkspaceSvg.newBlock (blockly_compressed.js:1310)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:972)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
    at Object.Blockly.Xml.domToBlockHeadless_ (blockly_compressed.js:975)
value @ BlocklyEditor.js:359
value @ BlocklyEditor.js:157
so @ react-dom.production.min.js:2837
Mi @ react-dom.production.min.js:3773
ji @ react-dom.production.min.js:3958
Ga @ react-dom.production.min.js:5512
$a @ react-dom.production.min.js:5534
Tl @ react-dom.production.min.js:5956
_l @ react-dom.production.min.js:5923
Il @ react-dom.production.min.js:6018
On @ react-dom.production.min.js:1737
i18n.js:41 Translate: Filter by
i18n.js:41 Translate: Close all but current`

**Comment by aleks-83** [comment]
> Ich nutze auch JS-controller 1.5.7 mit JS Adapter 4.1.0.
> Fast alle Skripte kann ich aufrufen, aber 2 nicht.
> Wenn ich auf JavaScript Anzeige umschalte, sehe ich den Code, schalte ich zurück (egal wie oft hin und her), bekomme ich die Meldung: Cannot extract blockly Code.
> 

Habe gerade den JS Adapter auf 4.1.4 geupdatet.

Fehler behoben !!!
Danke
