### ISSUE TITLE
Teilweise können Blockly Scripte nicht angezeigt werden, mit 4.1.2 selbes Verhalten

### ISSUE THREAD

**Issue by ihavenonick** [ioBroker/ioBroker.javascript#328]
[https://forum.iobroker.net/topic/20134/java-script-adapter-4-1-0-mit-bug/11](url)
![grafik](https://user-images.githubusercontent.com/36501310/53114805-ed7dbe80-3544-11e9-8e00-dcc47a686d79.png)

**Comment by Ilovegym66** [comment]
aktuell in der 4.1.0 ganz extrem, während die 4.0.12 diesen Fehler gar nicht hat (zumindest bei mir mit js-controller 1.5.7). 
In der 4.1.0 ist das bearbeiten von vorhandenen Blockly kaum möglich, da manche nicht extrahiert werden können.
( in der Browserkonsole steht dann was von zugriff verweigert... anscheinend ein Rechte-Problem? Habe es mit und ohne Expertenmodus probiert. )

**Comment by GermanBluefox** [comment]
Bitte unbedingt die Browser console beobachten

**Comment by Rantanplan01** [comment]
#326

**Comment by ihavenonick** [comment]
Das dürfte die Ursache sein, da alle Blocklys die nicht angezeigt werden könmem, diesen Baustein enthalten.

**Comment by Ilovegym66** [comment]
So, hier wie gewünscht aus Version 4.1.2 die Meldungen aus der Browserconsole, ich muss noch herausfinden, was der Unterschied zwischen den Blocklys ist, da 90% funktionieren, aber einige eben mit einem "cannot extract blockly code" enden. Man kann sie auch garnicht öffnen, egal wie oft ich hin und her klicke.

`Subscribe logs main.3dd41383.chunk.js:1:273429
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_EQ}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_NEQ}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LT}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_LTE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GT}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_COMPARE_TOOLTIP_GTE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_AND}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_LOGIC_OPERATION_TOOLTIP_OR}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_WHILE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_FOR_TOOLTIP}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_CONTROLS_FOREACH_TOOLTIP}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_ADD}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MINUS}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_MULTIPLY}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_DIVIDE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ARITHMETIC_TOOLTIP_POWER}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ROOT}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_ABS}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_NEG}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_LOG10}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_EXP}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_SINGLE_TOOLTIP_POW10}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_SIN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_COS}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_TAN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ASIN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ACOS}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_TRIG_TOOLTIP_ATAN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_SUM}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MIN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MAX}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_AVERAGE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MEDIAN}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_MODE}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_STD_DEV}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_ONLIST_TOOLTIP_RANDOM}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_MATH_CHANGE_TOOLTIP}. blockly_compressed.js:893:280
WARNING: No message string for %{BKY_TEXT_APPEND_TOOLTIP}. blockly_compressed.js:893:280
Detected custom blockly: cloud main.3dd41383.chunk.js:1:132126
Detected custom blockly: iot main.3dd41383.chunk.js:1:132126
Detected custom blockly: email main.3dd41383.chunk.js:1:132126
Translate: Filter by main.3dd41383.chunk.js:1:66785
Translate: Filter by
main.3dd41383.chunk.js:1:66785
Translate: Filter by main.3dd41383.chunk.js:1:66785
<unavailable> main.3dd41383.chunk.js:1:127794
Translate: Filter by
main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
Translate: Filter by main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
Attempt to set a forbidden header was denied: Connection 3711761521-lcs_client_bin.js:134:386
Attempt to set a forbidden header was denied: Connection 3711761521-lcs_client_bin.js:134:386
Translate: Filter by
main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
<unavailable> main.3dd41383.chunk.js:1:127794`

**Comment by ihavenonick** [comment]
Schau mal bitte ob bei Dir auch nur Blocklys betroffen sind die den von Rantanplan oben verlinkten Block enthalten, dann wäre das Problem sehr eng eingegrenzt.
Bei mir trifft das nämlich zu.

**Comment by Ilovegym66** [comment]
Hab mal etliche Scripte in beiden Versionen ( hab ne Testinst. mit V4.1.2 und mein Hauptsystem mit 4.0.12 ) zum Vergleichen angeschaut, es ist leider! nicht der Zwischen-Zeit-Block..  es sind Scripte mit diesem, aber auch ohne, die sich nicht öffnen lassen. Sogar einfache, nur falls-abfrage, dann Telegramm-Message. 
:-(

**Comment by Rantanplan01** [comment]
@Ilovegym66 Kann ich bei mir nicht nachvollziehen. Habe hier ca. 200 Scripte die sich ohne Probleme öffnen lassen. Arbeite haupsächlich mit Firefox.
Vor längerer Zeit hatte ich auch mal diese Probleme. Da hat ein leeren vom Browser Cache geholfen.

**Comment by Ilovegym66** [comment]
@Rantanplan01 leider hilft das nicht, verwende auch Firefox und habe ja gleichzeitig die alte 4.0.12 und neue Version 4.1.2 in verschiedenen Tabs offen, bei der alten kann ich die Scripte problemlos öffnen, in der neuen Version nicht.  Nee, den Browser schliesse ich aus, mit Chrome ist es gleich.
Sieht mir eher was mit Zugriffsrechten aus, vielleicht wurden die einen Scripts im Expertenmodus erstellt und die anderen nicht, weils den damals noch nicht gab oder so..

**Comment by ihavenonick** [comment]
Mit dem Browser hat das wohl nichts zu tun. Mit Firefox lassen sich die Scripte schließlich auch nach einem Downgrade vom JS Adapter wieder öffnen.

**Comment by Rantanplan01** [comment]
@Ilovegym66 Der Expertenmodus im Blockly Editor? Der blendet doch nur den Ordner "global" ein und aus.
Oder macht der auch noch was anderes?

**Comment by Ilovegym66** [comment]
@Rantanplan01 eigentlich nicht, seitdem exestiert das Problem...
@GermanBluefox hier nochmal was aus der Browserconsole, ich hoffe, man kann etwas damit anfangen, ich habe erst ein Blockly geöffnet, das nicht geht, dann eins, das geht:

`Attempt to set a forbidden header was denied: Connection
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://collector.githubapp.com/github-external/browser_event. (Reason: CORS request did not succeed).[Learn More]
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://api.github.com/_private/browser/stats’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).[Learn More]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://collector.githubapp.com/github-external/browser_event. (Reason: CORS request did not succeed).[Learn More]
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://api.github.com/_private/browser/stats’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).[Learn More]
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 134"  data: no]
Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars1.githubusercontent.com/favicon.ico (“default-src”).
Translate: Filter by
main.3dd41383.chunk.js:1:66785
<unavailable> main.3dd41383.chunk.js:1:127794
Translate: Filter by
main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
<unavailable> main.3dd41383.chunk.js:1:127794
Translate: Filter by main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
Translate: Filter by
main.3dd41383.chunk.js:1:66785
Translate: Close all but current main.3dd41383.chunk.js:1:66785
Translate: Filter by main.3dd41383.chunk.js:1:667851
Translate: Close all but current main.3dd41383.chunk.js:1:66785
Attempt to set a forbidden header was denied: Connection 3711761521-lcs_client_bin.js:134:386`

**Comment by ihavenonick** [comment]
(bleufox) fixed one error with "cannot extract blockly"
Definitiv nicht gefixt. Die selben Blockly lassen sich immer noch nicht öffnen und bei mir sind ausschließlich Blocklys betroffen die diesen Block beinhalten:
![grafik](https://user-images.githubusercontent.com/36501310/53176417-510ff680-35ee-11e9-92dc-9f88928fba64.png)
Es wäre mehr als ein Zufall, wenn es damit nichts zu tun hätte.

**Comment by gitbreiti** [comment]
Sieht bei mir genauso aus, sobald der Aktuelle Zeit zwischen x und y drin ist kann ich den blockly nicht mehr öffnen.

**Comment by hoaloha** [comment]
> (bleufox) fixed one error with "cannot extract blockly"
> Definitiv nicht gefixt. Die selben Blockly lassen sich immer noch nicht öffnen und bei mir sind ausschließlich Blocklys betroffen die diesen Block beinhalten:
> ![grafik](https://user-images.githubusercontent.com/36501310/53176417-510ff680-35ee-11e9-92dc-9f88928fba64.png)
> Es wäre mehr als ein Zufall, wenn es damit nichts zu tun hätte.

Mit diesem Block ist es definitiv reproduzierbar bei mir.

**Comment by GermanBluefox** [comment]
OK. Damit kann ich auch jetzt reproduzieren. Danke

**Comment by ihavenonick** [comment]
Problem wurde mit 4.1.3 gelöst

**Comment by andromedi4** [comment]
@GermanBluefox 
Problem "Cannot extract Blockly code!" still have in 4.1.3, and this problem with time block!
How I can repair it?
![image](https://user-images.githubusercontent.com/43029169/53287198-a3394f00-3789-11e9-95ea-52e629be7b55.png)
