### ISSUE TITLE
createState in 0_userdata.0 ermöglichen

### ISSUE THREAD

**Issue by SBorg2014** [ioBroker/ioBroker.javascript#429]
createState sollte auch im neuen "0_userdata.0"-Ordner anwendbar sein und nicht nur innerhalb der javascript.x-Instanz.

**Comment by Apollon77** [comment]
am besten vllt als "createUserState"-Methode?

**Comment by SBorg2014** [comment]
Paul53 kennt sich da "bisserl besser" aus. Würde es zumindest deutlich abgrenzen, allerdings muss ich eh den kpl. Objektpfad angeben und würde es so auch sehen.

**Comment by Mic-M** [comment]
👍 
Hier übrigens ein Script (Workaround), mit dem es im JS-Adapter geht: https://github.com/Mic-M/iobroker.createUserStates
Entstanden hier: https://forum.iobroker.net/topic/26839/

**Comment by hsteinme** [comment]
Ich möchte gern dieses Thema aufwärmen und wieder in Erinnerung rufen.

Es kam bei mir Freude auf, als ich die Ankündigung von 0_userdata.0 und dessen Funktionalität als benutzereigener Datenpunktbaum im Rahmen der ioBroker Version 2 gelesen hatte - weil dieses Konstrukt mir als Javascript-User mehr Sicherheit bringt. Als jedoch nach dem Upgrade auf Version 2 ein erster Test mit einem simplen Statement der Art 

`createState('0_userdata.0.Test123');`

ein ungewolltes Ergebnis lieferte (nämlich einen Datenpunkt javascript.0.0_userdata.0.Test123), wandelte sich meine Freude in "Unfreude". Laut den Diskussionen im [Forum](https://forum.iobroker.net/topic/26759/js-controller-2-jetzt-f%C3%BCr-alle-im-stable/) soll ja das 0_userdata.0-Konstrukt gerade Einsteiger "anlocken". Um so wichtiger ist es daher, den Einsteigern auch ein einfaches Grundgerüst an Werkzeugen hierfür in die Hand zu geben.

Ansätze der Art, wir führen ein neues Statement createUserState() ein, führen daher m.E. in die falsche Richtung. Wo ist aus Javascript-Anwendersicht der Unterschied zwischen Datenpunkten unter 0_userdata.0, unter javascript.x oder unter z.B. radar2.x? Aus meiner Anwendersicht gibt es da keine wesentlichen Unterschiede. Daher sollten auch die zugehörigen Werkzeuge keine wesentlichen Unterschiede aufweisen bzgl. z.B. Verfügbarkeit, Funktionalität, Syntax, ...

Ich weiß, dass alle am ioBroker-Projekt Entwickelnden dies in ihrer Freizeit tun (wofür ich hier auch mal ein dickes "Danke schön" los werden möchte). Die Zeit ist ein wertvolles Gut und kann nicht so ohne weiteres vermehrt werden. Aber die Verfügbarkeit von neuen Funktionen, Erweiterungen, Fehlerbehebungen, ... hängt nicht nur vom benötigten Aufwand ab, sondern auch von den vergebenen Prioritäten. In diesem Sinne bitte ich herzlich darum, die Priorität dieses Issues einem Review zu unterziehen.

Just my 0.02 €.

**Comment by sync85** [comment]
muss schauen wie ich das mit debug mache so sieht es bei mir beim start aus:

tuya.0 | 2020-07-08 07:03:15.325 | info | (10444) bfddb46624b6c34ca2hnrr Init with IP=192.168.0.24, Key=002e4adc2b3c64b4, Version=3.3
-- | -- | -- | --
tuya.0 | 2020-07-08 07:03:15.295 | info | (10444) 70770354c44f33ad0ec1: None of the discovered devices matches :-(
tuya.0 | 2020-07-08 07:03:15.293 | info | (10444) 08207108600194cbf402: None of the discovered devices matches :-(
tuya.0 | 2020-07-08 07:03:15.084 | info | (10444) Listen for encrypted local Tuya devices on port 6667
tuya.0 | 2020-07-08 07:03:15.083 | info | (10444) Listen for local Tuya devices on port 6666
tuya.0 | 2020-07-08 07:03:15.070 | info | (10444) Existing devices initialized
tuya.0 | 2020-07-08 07:03:15.067 | info | (10444) 70770354c44f33ad0ec1 Init with IP=192.168.0.65, Key=12b5cfda96e3bb02, Version=3.3
tuya.0 | 2020-07-08 07:03:15.059 | info | (10444) 08207108600194cbf402 Init with IP=192.168.0.26, Key=cd3888c830c71530, Version=3.3
tuya.0 | 2020-07-08 07:03:15.022 | info | (10444) bfddb46624b6c34ca2hnrr Init with IP=192.168.0.24, Key=002e4adc2b3c64b4, Version=3.3
tuya.0 | 2020-07-08 07:03:14.466 | info | (10444) starting. Version 3.3.7 in /opt/iobroker/node_modules/iobroker.tuya, node: v10.21.0, js-controller: 3.1.4
tuya.0 | 2020-07-08 07:03:14.400 | info | (10444) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system

das ist die Lampe die vorher gesponnen hatte: bfddb46624b6c34ca2hnrr

hoffe das hilft etwas geh später sonst nochmal schauen wegen debug und so :)

**Comment by MartinP1** [comment]
In der aktuellen Version stimmt das von @hsteinme geschriebene nicht mehr!

Ich möchte gern dieses Thema aufwärmen und wieder in Erinnerung rufen.

```createState("0_userdata.0.blablastate", {type: 'boolean' });```

führt NICHT mehr  zum Kreieren eines Datenpunktes "javascript.0.0_userdata.0.blablastate", sondern wie gewünscht ...

```
{
  "0_userdata.0.blablastate": {
    "common": {
      "type": "boolean",
      "name": "0_userdata.0.blablastate",
      "role": "state"
    },
    "native": {},
    "type": "state",
    "from": "system.adapter.javascript.0",
    "user": "system.user.admin",
    "ts": 1731407544046,
    "_id": "0_userdata.0.blablastate",
    "acl": {
      "object": 1636,
      "state": 1636,
      "owner": "system.user.admin",
      "ownerGroup": "system.group.administrator"
    },
    "ack": false
  }
}```

**Comment by klein0r** [comment]
@MartinP1 Ja, deswegen ist der Issue vor über 4 Jahren geschlossen worden?!
