### ISSUE TITLE
"t.indexOf is not a function" in Connection.js:140

### ISSUE THREAD

**Issue by fbeister** [ioBroker/ioBroker.javascript#510]
ioBroker.js-controller = 2.2.9
ioBroker.javascript = 4.3.4

I have to use 4.3.4 due to #509 so I run into the following problem (which is fixable by reloading and no longer present in 4.4.2):

```
    this.socket.on('error', function (err) {
      if (err.indexOf('User not authorized') !== -1) {
        _this.authenticate();
      } else {
        window.alert(err);
      }
    });
```

The error is pointing to the line `if (err.indexOf`...

This might already be solved in later versions but as a reference it might be nice to have the version it was fixed in referenced here. I could not find anything in the changelog or the issue tracker.

**Comment by Apollon77** [comment]
While downgrading JS to 4.3. you also need to downgrade admin to <4.0 and iot and devices and all of these. Becaus ethis issue only seems to happen with the new soekcet.io library introcuced in all those adapters and is now caused by that "socket.io version mixture" I guess.

And in fact the but in #509 should also appeas in 4.3 if it is there. There was no change in 4.4.x which affected setState logic - all changes here were in other parts.

**Comment by fbeister** [comment]
I feared that this would be the answer - for now this is the only annoyance I encountered with my combination of versions (4.3.4 with latest admin) so I'll just leave it as-is and hope for a solution for #509
